### ISSUE TITLE
PR #5 messed up previous styling and card styling attributes aren't documented

### ISSUE THREAD

**Issue by rpitera** [custom-cards/canvas-gauge-card#10]
Had a beautiful compass going and although it wasn't centered it still looked great.  Updated to the latest version via HACS and now I have a white background.  Not sure how to change the background of the card back to the previous transparency because there's no documentation on the new card styling attributes.  Could use some help.  I mean, I appreciate that it's centered now, but the white bg is killing me.

Tried using:

```
style:
  background-color:
```
with both a color name and with rgba coloring, neither worked.
```
      - type: custom:canvas-gauge-card
        entity: sensor.wind_compass
        gauge:
          type: "radial-gauge"
          height: 250
          width: 250
          minValue: 0
          maxValue: 360
          majorTicks: ["N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"]
          minorTicks: 22
          ticksAngle: 360
          valueBox: false
          startAngle: 180
          strokeTicks: false
          highlights: false
          colorPlate: "rgba(0, 0, 0, .1)"
          colorMajorTicks: "#447BC3"
          colorMinorTicks: "#ddd"
          colorNumbers: "#447BC3"
          colorNeedle: "rgba(240, 128, 128, 1)"
          colorNeedleEnd: "rgba(255, 0, 0, .9)"
          valueTextShadow: false
          colorCircleInner: "#000"
          colorNeedleCircleOuter: "#ccc"
          needleCircleSize: 1
          needleCircleOuter: false
          animationRule: "linear"
          needleType: "line"
          needleStart: 75
          needleEnd: 99
          needleWidth: 3
          borders: true
          borderInnerWidth: 0
          borderMiddleWidth: 0
          borderOuterWidth: 5
          colorBorderOuter: "#447BC3"
          colorBorderOuterEnd: "#447BC3"
          colorNeedleShadowDown: "#222"
          borderShadowWidth: 0
          animationDuration: 1500
```
