### ISSUE TITLE
Cannot add property borderShadowWidth, object is not extensible

### ISSUE THREAD

**Issue by volshebniks** [custom-cards/canvas-gauge-card#18]
After upgrade to 0.106.0 a have this Error:
Cannot add property borderShadowWidth, object is not extensible

**Comment by bmorgan99** [comment]
I got the same thing initially, removed all the border* options and got "Custom element doesn't exist: canvas-gauge-card."

**Comment by volshebniks** [comment]
I'vу temporarily set border = true. It's works without any errors, but I don't like such design.

**Comment by volshebniks** [comment]
I'vу temporarily set border = true. It's works without any errors, but I don't like such design.

**Comment by rpitera** [comment]
@volshebniks - So with the ugly border though, it does still load properly in 0.106.0?  I can live with design faults until the card is updated per Thomas comments in #15 as long as I'm still able to use the card.

**Comment by bmorgan99** [comment]
I stripped all but the essentials out, cleared the cache and restarted HA but still no love.

**Comment by aerastov** [comment]
borders: true
borderOuterWidth: 0
borderMiddleWidth: 0
borderInnerWidth: 0
borderShadowWidth: 0

**Comment by helto4real** [comment]
@aerastov , @rpitera  can you please test the version by copy the "canvas-gauge-card.js" in the v106fix branch to the correct place in Home Assistant. Make sure that your browser is not caching by clearing cache. 

The ugly border can be removed by  using:
```yaml
          borderShadowWidth: 0
          borderOuterWidth: 0
          borderMiddleWidth: 0
          borderInnerWidth: 0
```

The fix is here (not merged to the master yet, needs testing)
[https://github.com/custom-cards/canvas-gauge-card/tree/v106fix](https://github.com/custom-cards/canvas-gauge-card/tree/v106fix)

**Comment by helto4real** [comment]
What I did was remove the code that got the error. I really dont need to access the configuration. The reason I did in the first place was to compensate for a bug in gauge code that did not remove borders on `borders: false` config. There are a fix to remove borders by setting
```yaml
- type: "custom:canvas-gauge-card"
        card_height: 125
        entity: sensor.memory_use_percent
        gauge:
          borderShadowWidth: 0
          borderOuterWidth: 0
          borderMiddleWidth: 0
          borderInnerWidth: 0
...

 ```
I recon people want to get the gauges working again and I will look for a more permanent solution when I get the time... Not making promises.
