### ISSUE TITLE
Not working in Home Assistant 0.106.5

### ISSUE THREAD

**Issue by kmacena** [custom-cards/canvas-gauge-card#21]
From developer logs: /lovelace/home:0:0 Uncaught TypeError: Failed to resolve module specifier "canvas-gauges". Relative references must start with either "/", "./", or "../". 
From Lovelace UI: Cannot read property 'setConfig' of undefined.
Downloaded RAW version from GIT.

**Comment by HFsi** [comment]
Same here.
Installed through HACS.
Error: Cannot assign to read only property 'borderShadowWidth' of object '#<Object>'

**Comment by plutosherry** [comment]
same error in HA106.6

**Comment by opep** [comment]
Same here.
Since 0.106 some changes were made to the code which affect custom cards:
https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes.html

**Comment by helto4real** [comment]
You guys still have same issue?
Also please check you configured correctly...

```yaml
lovelace:
  mode: yaml
  resources:
     - url: /local/custom_cards/canvas-gauge-card.js
       type: module
```
This is done int configuration.yaml please check
