### ISSUE TITLE
Top left quadrant has wrong image

### ISSUE THREAD

**Issue by Claws81** [custom-cards/canvas-gauge-card#22]
Hi. I just installed your plugin via HACS (thanks for making it!), but after a short while, the rendered gauge displays the wrong image in the top left q. 
It displays the image from the bottom right q instead it seems.
I don't know if this is an issue with your plugin, Home Assistant or the canvas gauges themselves, but you might be the right person to ask.

Configuration for radial gauge included here:
```
- type: 'custom:canvas-gauge-card'
        entity: sensor.phantom_temp
        card_height: 175
        gauge:
          type: radial-gauge
          title: Phantom MQTT temperature sensor (C)
          width: 200
          height: 200
          borderShadowWidth: 0
          borderOuterWidth: 0
          borderMiddleWidth: 0
          borderInnerWidth: 0
          minValue: -200
          maxValue: 200
          startAngle: 45
          ticksAngle: 270
          valueBox: false
          majorTicks:
            - '-200'
            - '-175'
            - '-150'
            - '-125'
            - '-100'
            - '0'
            - '10'
            - '125'
            - '150'
            - '175'
            - '200'
          minorTicks: 2
          strokeTicks: true
          highlights:
            - from: 150
              to: 200
              color: 'rgba(200, 50, 50, .75)'
          borders: false
```
![Screenshot_20200319_104452](https://user-images.githubusercontent.com/20287284/77053683-01f1ec00-69cf-11ea-9d7e-e927e6a51cd2.png)
