### ISSUE TITLE
Error resolving module specifier: canvas-gauges

### ISSUE THREAD

**Issue by electron64** [custom-cards/canvas-gauge-card#26]
Hello , i followed the instructions to install it and i get this error in logs and in editor it says:

`version= Home Assistant 0.103.6
os=Ubuntu 18.04`

`Custom element doesn't exist: canvas-gauge-card.`

`http://192.168.1.108:8123/local/custom_cards/canvas-gauge-card/canvas-gauge-card.js:25:18 TypeError: Error resolving module specifier: canvas-gauges`

I added the file .js and i can reach it via url .
Do someone know how i can fix it please?

**Comment by helto4real** [comment]
```yaml
lovelace:
  mode: yaml
  resources:
     - url: /local/custom_cards/canvas-gauge-card.js
       type: module
```
This is done int configuration.yaml please check
