### ISSUE TITLE
Half and full gauge mix up

### ISSUE THREAD

**Issue by barto64** [custom-cards/canvas-gauge-card#34]
If you have several graphs across different views it looks like the first one you look at make the set-up of the full or half gauge across all the session for all the graphs you had. This way if the first one you look is a half all other full graphs you have in other views will appear only half losing half of it and viceversa, if the first one you look is full you will see all other half as if they were full with the lowest part empty.

Hope I had been able to explain it well.

Thanks

**Comment by Olen** [comment]
I think this is i more general problem when having multiple gauges.
Some values for the settings seems to be inhertied from the _first_ instance of a gauge-card that is created.
I have a page with many gauges, some radials, some linears.
ALL the gauges seems to inherit at least the "width" and "height" value from the first one.  So if the first gauge in my config is "gauge.width: 220", then all the other gauges get the same width, no matter what I set in the config.

The really strange issue is that this only affects the css part of the card code.  I have looked at the source and can not understand why this is happening as they seem to be using the same variable in the javascript (`${this._gaugeWidth}`).

Consider the following:

```
      - type: 'custom:canvas-gauge-card'
        card_height: 225
        gauge:
          type: radial-gauge
          height: 220
          width: 220
(...)

      - type: 'custom:canvas-gauge-card'
        card_height: 223
        gauge:
          type: linear-gauge
          height: 200
          width: 100
```
For the first card, I get the following:
```
<style>
#cardroot {
  width: 220px;
  height: calc(225px + 0px);
}
#container {
  width: 220;
  height: 225px;
}

</style>
<div id="cardroot">
  <div id="container" width="220" height="225">
    <div id="innercontainer" width="220" height="225">
(...)
```
Which is correct.

But for the second gauge I get the following:
```
<style>
#cardroot {
  width: 220;
  height: calc(225px + 0px);
}
#container {
  width: 220;
  height: 225px;
}

</style>
<div id="cardroot">
  <div id="container" width="100" height="223">
    <div id="innercontainer" width="100" height="223">
(...)
```

So the width and height set in the div-tags are correctly set from the card config.  But the wdth and height in css in the style-section is from the FIRST card that is configured (verfied by changing the config of the first card, and watching the width of all the gauges change.
