### ISSUE TITLE
Card width does not seem to work | gauge disappears

### ISSUE THREAD

**Issue by xbmcnut** [custom-cards/canvas-gauge-card#35]
Hi there,

Love this card so thank you for making it. 

I had a gauge for my Weber iGrill configured in panel mode in its own LL tab with very large height and width so my wife could see it across the room. LL would switch to this tab when the bluetooth thermometer comes online. Lately, don't know when, the gauge disappeared and will only display if I reduce the height/width to 220/220 or something similar.

This is what I had working in panel mode. I'm running under HACS with version 0.4 sitting on HA 0.111.3
```
entity: sensor.igrill_thermometer
font_size: 1em
gauge:
  animatedValue: true
  borders: true
  colorBorderInner: '#111'
  colorBorderInnerEnd: '#333'
  colorBorderMiddle: '#222'
  colorBorderMiddleEnd: '#111'
  colorBorderOuter: '#333'
  colorBorderOuterEnd: '#111'
  colorNumbers: '#ccc'
  colorPlate: ''
  colorTitle: '#f5f5f5'
  colorUnits: '#f5f5f5'
  height: 720
  highlights:
    - color: 'rgba(0, 68, 255, .75)'
      from: 5
      to: 38
    - color: 'rgba(4, 205, 24, .75)'
      from: 38
      to: 41
    - color: 'rgba(239, 93, 13, .75)'
      from: 41
      to: 45
  majorTicks:
    - '5'
    - '10'
    - '15'
    - '20'
    - '25'
    - '30'
    - '35'
    - '40'
    - '45'
  maxValue: 45
  minValue: 5
  minorTicks: 5
  startAngle: 45
  strokeTicks: true
  ticksAngle: 270
  title: Spa Temp
  type: radial-gauge
  units: °C
  valueBox: true
  valueDec: 1
  valueInt: 2
  width: 600
type: 'custom:canvas-gauge-card'
```

**Comment by Olen** [comment]
Pretty sure this is related to #34 
Sometihng odd is going on with the CSS bit of this card sometime around HA 110 or 111.

**Comment by Olen** [comment]
You can probably see it if you go into developer mode in your browser and "inspect element" of the gauge.  I guess you will see that the <div> tags have the correct width/height in the actual tag, but looking at the css for the tags shows another width/height (actually it should probably be the width/height for the first canvas-gauge in the dahsboard).

I believe you can solve this exact issueif you move this gauge on a dedicatd dashboard (lovelace supports more than one dahsboard now) instead of a tab in another dashboard.

**Comment by xbmcnut** [comment]
Thanks. I tried moving my gauge onto its own tab with no other entities and that does not work. Let me try a complete new dashboard as I have not tried that.

**Comment by xbmcnut** [comment]
Sorry, tried new dash and does not work there either. Not much of a coder too sorry so unsure how to use the inspector to find what I'm looking for.

**Comment by xbmcnut** [comment]
I accidentally dragged some code around when trying to copy the problem code using the inspector and the bloody gauge popped back full size. Don't know what I did. Displays properly now in FF and Chrome. The code block I messed with is below and trying to me doing something, the width was reporting as 200px.

![image](https://user-images.githubusercontent.com/1492137/84761231-436d5400-b01d-11ea-9862-8d203aa9677e.png)

**Comment by helto4real** [comment]
Good to hear it all worked out. Yea I seen problems in the IOS app displaying gauges too

**Comment by xbmcnut** [comment]
Wish I knew what I did! 🥴

**Comment by GHSTUDIO1** [comment]
did you ever figure this out....I'm trying to do a display for a Maverick et-732 thermometer :)

**Comment by GHSTUDIO1** [comment]
There is an error in the code.

In /config/www/guage-card.js, there is a statement
```
}

  getCardSize() {
    return 1;
  }
```
which says essentially, the card size is one unit height.  Change that 1 to a 2.  It's not the right answer, but it's an effective temporary work around.  It probably will effect all gauges which will now take 2 height units.  Hopefully the developer will figure out the correct entry for getCarSize.

**Comment by xbmcnut** [comment]
> 
> 
> did you ever figure this out....I'm trying to do a display for a Maverick et-732 thermometer :)

I moved to custom:flex-horseshoe-card which solved my requirement for a super large thermometer display.

**Comment by Olen** [comment]
I made it work here by editing canvas-gauge-card.js and removing the "width"-definitions from the CSS for #cardroot and #container around line 250 in the js-file.
```
         #cardroot {
-          width: ${this._gaugeWidth}px;

         #container {
-          width: ${this._gaugeWidth}px;
```
(Remove the two lines starting with "-")

There is also a typo in the code (see here: https://github.com/custom-cards/canvas-gauge-card/pull/37/commits/41db5d559c4b93db5b4bfecbfc1b2ae5d8def6d9) and you can find it by searching for wid**ht** and replacing it with "wid**th**"
You need to "shift reload" before the new JS is replaced. 
At least my gauges are now behaving correctly.

**Comment by helto4real** [comment]
Thanks I will check this out and deploy new version

**Comment by helto4real** [comment]
Made new version now

**Comment by Olen** [comment]
I don't think fixing the typo alone is enough to fix the issue with the width, unless that fix in the typescript file trickle down to multiple other fixes in the generated .js
(I'll look at the new version later)

**Comment by GHSTUDIO1** [comment]
I can confirm that it doesn't work.  Here's my lovelace configuration file....only part of the gauge shows. (pick the sensor of your choice to test it).  Note: if I make width/height 200, the whole gauge shows.

```
views:
  - cards:
      - entity: sensor.acurite_temperature
        font_size: 1em
        gauge:
          animatedValue: true
          borders: false
          colorBorderInner: '#111'
          colorBorderInnerEnd: '#333'
          colorBorderMiddle: '#222'
          colorBorderMiddleEnd: '#111'
          colorBorderOuter: '#333'
          colorBorderOuterEnd: '#111'
          colorNumbers: '#ccc'
          colorPlate: ''
          colorTitle: '#f5f5f5'
          colorUnits: '#f5f5f5'
          height: 400
          maxValue: 350
          minValue: 50
          minorTicks: 5
          startAngle: 45
          strokeTicks: true
          ticksAngle: 270
          title: Grill Temp
          type: radial-gauge
          units: °F
          valueBox: true
          valueDec: 1
          valueInt: 2
          width: 400
        type: 'custom:canvas-gauge-card'
```

**Comment by Olen** [comment]
I really don't understand why the width specified in the div-tag and the one specified in the CSS for the same element are different.
They seem to use the exact same variable in the TS-file.
It almost looks like the CSS-part of the card is inherited from the first card, and overwritten after the card is initialized.

**Comment by GHSTUDIO1** [comment]
I believe the size of the panel is determined the very first time you open the page....and once you've done that, you can't increase (or decrease) the size of the meter panel.  I did a complete reinstall for other reasons, and when I started the script above, suddenly the panel was larger...and the full meter displayed.  Trying to make it larger resulted in part being cut off because the panel size is now fixed.

**Comment by Olen** [comment]
The CSS-part of a card:
![image](https://user-images.githubusercontent.com/203184/90318272-d0eef680-df2f-11ea-8136-3a9b74a15ab3.png)

And the DIV-tags:
![image](https://user-images.githubusercontent.com/203184/90318322-009dfe80-df30-11ea-88b0-49690be16dc3.png)

Watch how *#cardroot* and *#container* has `width: 220px` in the CSS but the container div has `width="120"
The cardroot-div does not specify a width.

I believe this happens because I have multiple canvas-gauges on the page, and some are 220 wide:
```
      - card_height: 225
        type: 'custom:canvas-gauge-card'
        entity: sensor.foo
        gauge:
          height: 220
          width: 220

(...)
```
while other cards are narrower:
```
          - type: 'custom:canvas-gauge-card'
            card_height: 223
            card_width: 120
            font_size: 1em
            shadow_top: 20
            entity: sensor.bar
            gauge:
              type: linear-gauge
              width: 100
              height: 200
(...)
```

And for some reason the narrow cards inherit the width from the wide cards, but only in the CSS, not in the div tag.
