### ISSUE TITLE
Unable to set max properly

### ISSUE THREAD

**Issue by lgwapnitsky** [custom-cards/canvas-gauge-card#50]
I'm trying to set my max value, but I'm unable to get beyond 100.

Code:
```

type: custom:canvas-gauge-card
entity: sensor.air_quality_index
card-height: 125
gauge:
  type: radial-gauge
  title: AQI
  minValue: 0
  maxValue: 300
```

What I'm seeing:

![Screenshots_2022-06-14-07-47-41](https://user-images.githubusercontent.com/647444/173571042-d97e6ba2-a81b-48de-bccb-39e1fb035ca7.png)
