### ISSUE TITLE
Cannot display attribute

### ISSUE THREAD

**Issue by lloyda** [custom-cards/canvas-gauge-card#51]
I'm trying to move from tempometer-gauge to these gauges.  In tempometer I can specify the entity as climate.evohome_cc_01_185426_00.current_temperature, but if I try and use this entity with canvas gauges I simply get a blank card, and I cannot work out the correct syntax to use to make it work.

**Comment by xbmcnut** [comment]
Code below for this. Maybe it helps?
![image](https://user-images.githubusercontent.com/1492137/196918314-40ae7952-1187-4d74-a519-8e5f5d0329f6.png)
```
  - type: custom:canvas-gauge-card
    entity: sensor.temperature_xiaomi_outside
    font_size: 1em
    gauge:
      animatedValue: true
      borders: true
      colorBorderInner: '#111'
      colorBorderInnerEnd: '#333'
      colorBorderMiddle: '#222'
      colorBorderMiddleEnd: '#111'
      colorBorderOuter: '#333'
      colorBorderOuterEnd: '#111'
      colorNumbers: '#ccc'
      colorPlate: ''
      colorTitle: '#f5f5f5'
      colorUnits: '#f5f5f5'
      height: 240
      width: 240
      highlights:
        - color: rgba(0, 68, 255, .75)
          from: 0
          to: 5
        - color: rgba(74, 123, 180, .75)
          from: 5
          to: 15
        - color: rgba(4, 205, 24, .75)
          from: 15
          to: 25
        - color: rgba(239, 93, 13, .75)
          from: 25
          to: 40
      majorTicks:
        - '0'
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
      maxValue: 40
      minValue: 0
      minorTicks: 5
      startAngle: 45
      strokeTicks: true
      ticksAngle: 270
      title: Outside Temp
      type: radial-gauge
      units: °C
      valueBox: true
      valueDec: 1
      valueInt: 2
```
