### ISSUE TITLE
Position of numbers in Radial gauge

### ISSUE THREAD

**Issue by Protoncek** [custom-cards/canvas-gauge-card#65]
Hi!
I'm struggling with pretty small gauge in Home Assistant - i can't position numbers closer to ticks (away from center). Is there any command/setting for that? See picture - i'd like numbers to be just under ticks, not so near needle center. Is this possible? I've went through pretty much all commands i've found. I think my problem is that i have small gauge, and it's inside Home Assistant's picture elements:

```
          - type: custom:canvas-gauge-card
            entity: sensor.temperatura_dviznega_voda
            card_height: 90
            gauge:
              type: radial-gauge
              width: 90
              height: 90
              colorMinorTicks: white
              colorMajorTicks: white
              colorNumbers: white
              fontNumbersSize: 35
              borderShadowWidth: 0
              borderOuterWidth: 0
              borderMiddleWidth: 0
              borderInnerWidth: 0
              borders: false
              minValue: 20
              maxValue: 80
              startAngle: 90
              ticksAngle: 180
              valueBox: false
              majorTicks:
                - '20'
                - '40'
                - '60'
                - '80'
              minorTicks: 4
              strokeTicks: false
              colorNeedle: black
              colorNeedleEnd: brown
              needleShadow: true
              colorPlate: transparent
              highlights:
                - from: 70
                  to: 80
                  color: darkred
```
![image](https://github.com/custom-cards/canvas-gauge-card/assets/26406640/b8a05d0a-38f8-4b1c-90e2-17d90c823658)
