### ISSUE TITLE
/local/gauge.min.js:28:0 SyntaxError

### ISSUE THREAD

**Issue by vpomax** [custom-cards/canvas-gauge-card#7]
I followed your instructions... I put canvas-gauge-card.js and gauge.min.js both in my Hassio (v. 0.83.2) folder    \config\www\
I edited ui_lovelace.yaml inserting...

```
resources:
  - url: /local/canvas-gauge-card.js
    type: module

      - type: custom:canvas-gauge-card
        entity: sensor.temperature_158d0002772a84
        name: Temperatura Esterna (%)
        card_height: 145
        shadow_height: 15%
        font_size: 1em
        gauge:
          type: "radial-gauge"
          width: 220
          height: 220
          minValue: -20
          maxValue: 50
          startAngle: 90
          ticksAngle: 180
          valueBox: false
          majorTicks: ["-30", "-20", "-10", "0", "10", "20", "30", "40", "50"]
          minorTicks: 2
          strokeTicks: true
          highlights: [{"from": 80, "to": 100,"color": "rgba(200, 50, 50, .75)"}]
          borders: false
```
but after reboot it is not displayed... 
and my Hassio I have the following error:

```
2018-12-06 11:24:35 ERROR (MainThread) [frontend.js.latest.201811211] https://xxx.duckdns.org/local/gauge.min.js:28:0 SyntaxError: illegal character
2018-12-06 11:28:39 ERROR (MainThread) [frontend.js.latest.201811211] https://xxx.duckdns.org/local/gauge.min.js:28:1 Uncaught SyntaxError: Invalid or unexpected token
```
